const express = require('express');
const router = express.Router();

const healthRoutes = require('./healthRoutes');
const uploadRoutes = require('./uploadRoutes');
const studentRoutes = require('./studentRoutes');
const authRoutes = require('./authRoutes');
const userRoutes = require('./userRoutes');
const blockRoutes = require('./blockRoutes');
const roleRoutes = require('./roleRoutes');
const academicYearRoutes = require('./academicYearRoutes');
const teacherRoutes = require('./teacherRoutes');
const parishRoutes = require('./parishRoutes');
const classRoutes = require('./classRoutes');
const scoreConfigRoutes = require('./scoreConfigRoutes');
const scoreRoutes = require('./scoreRoutes');
const scoreTypeRoutes = require('./scoreTypeRoutes');
const semesterRoutes = require('./semesterRoutes');
const attendanceConfigRoutes = require('./attendanceConfigRoutes');
const attendanceRecordRoutes = require('./attendanceRecordRoutes');
const attendanceSyncRoutes = require('./attendanceSyncRoutes');
const attendanceSyncProcessRoutes = require('./attendanceSyncProcessRoutes');
const gradeRoutes = require('./gradeRoutes');
const enrollmentRoutes = require('./enrollmentRoutes');
const dashboardRoutes = require('./dashboardRoutes');
const chatbotRoutes = require('./chatbotRoutes');

router.use('/auth', authRoutes);
router.use('/health', healthRoutes);
router.use('/upload', uploadRoutes);
router.use('/students', studentRoutes);
router.use('/users', userRoutes);
router.use('/blocks', blockRoutes);
router.use('/roles', roleRoutes);
router.use('/academic-years', academicYearRoutes);
router.use('/teachers', teacherRoutes);
router.use('/parishes', parishRoutes);
router.use('/classes', classRoutes);
router.use('/score-configs', scoreConfigRoutes);
router.use('/scores', scoreRoutes);
router.use('/score-types', scoreTypeRoutes);
router.use('/semesters', semesterRoutes);
router.use('/attendance-configs', attendanceConfigRoutes);
router.use('/attendance-records', attendanceRecordRoutes);
router.use('/attendance-sync-logs', attendanceSyncRoutes);
router.use('/attendance-sync', attendanceSyncProcessRoutes);
router.use('/grades', gradeRoutes);
router.use('/enrollments', enrollmentRoutes);
router.use('/dashboard', dashboardRoutes);
router.use('/chatbot', chatbotRoutes);

module.exports = router;
